### ISSUE TITLE
Regarding saving of audio

### ISSUE THREAD

**Issue by saurabhvyas** [desbma/GoogleSpeech#14]
Is there any way of saving the audio file on my linux computer ?

**Comment by desbma** [comment]
See here: https://github.com/desbma/GoogleSpeech/issues/3

Saving audio is not really supported, but you can still do it either by:
* running google_speech with `-v debug`, copy the URL, download it, and save it as an MP3 file
* doing a SQL request on the cache file, see here: https://github.com/desbma/GoogleSpeech/issues/3#issuecomment-206572836

**Comment by piegamesde** [comment]
Is there a possibility to dump the audio to stdout instead? `espeak` does this and it is great.

**Comment by desbma** [comment]
It it not currently possible, because the audio is made from several audio files for short segments. So one would have to merge them (without transcoding) and output them at the same time, while also handling the text input that can come from stdin.

**Comment by piegamesde** [comment]
What about a command line parameter where google_speech does not play any sound, but outputs all files it _would_ play to stdout (and nothing else)?

**Comment by desbma** [comment]
That would generate invalid audio data and no player would be able to read past the first file.

Concatenating 2 valid audio files does not necessarily result in a valid audio file, in fact for MP3 it is guaranteed to result in a corrupt file.
Only certain specific transport formats like MPEG-TS are designed with that propriety in mind, because they are used when broadcasting streams where packet loss is common, and clients can start reading the stream at any random point.
